import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import { z } from 'zod';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

const ComposeRequestSchema = z.object({
  jobId: z.string(),
  artistName: z.string(),
  releaseTitle: z.string().optional(),
  watermark: z.boolean().optional().default(true),
});

const EPK_TEMP_DIR = process.env.EPK_TEMP_DIR || '/tmp/thecueroom-epk';

async function stampPDF(
  inputPath: string,
  outputPath: string,
  artistName: string,
  releaseTitle?: string,
  watermark: boolean = true
): Promise<void> {
  const pdfBytes = await fs.readFile(inputPath);
  const pdfDoc = await PDFDocument.load(pdfBytes);
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  pdfDoc.setTitle(`${artistName}${releaseTitle ? ` - ${releaseTitle}` : ''} - EPK`);
  pdfDoc.setAuthor(artistName);
  pdfDoc.setSubject('Electronic Press Kit');
  pdfDoc.setKeywords([artistName, releaseTitle || '', 'EPK', 'Press Kit', 'Music'].filter(Boolean));
  pdfDoc.setProducer('thecueRoom');
  pdfDoc.setCreator('thecueRoom EPK Generator');

  const pages = pdfDoc.getPages();
  const firstPage = pages[0];
  const { width, height } = firstPage.getSize();

  firstPage.drawText(artistName, {
    x: 50,
    y: height - 50,
    size: 24,
    font: helveticaBold,
    color: rgb(0.84, 1.0, 0.24), // #D7FF3C
  });

  if (releaseTitle) {
    firstPage.drawText(releaseTitle, {
      x: 50,
      y: height - 80,
      size: 14,
      font: helveticaFont,
      color: rgb(0.61, 0.36, 1.0), // #9B5CFF
    });
  }

  if (watermark) {
    pages.forEach((page) => {
      const { width, height } = page.getSize();
      page.drawText('Generated by thecueRoom', {
        x: width - 200,
        y: 20,
        size: 10,
        font: helveticaFont,
        color: rgb(0.4, 0.4, 0.4),
        opacity: 0.5,
      });
    });
  }

  const stampedBytes = await pdfDoc.save();
  await fs.writeFile(outputPath, stampedBytes);
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { jobId, artistName, releaseTitle, watermark } = ComposeRequestSchema.parse(body);

    const jobDir = path.join(EPK_TEMP_DIR, jobId);
    const inputPdfPath = path.join(jobDir, 'epk.pdf');
    const outputPdfPath = path.join(jobDir, 'epk-stamped.pdf');

    try {
      await fs.access(inputPdfPath);
    } catch {
      return NextResponse.json({
        ok: false,
        error: 'PDF file not found for this job',
      }, { status: 404 });
    }

    await stampPDF(inputPdfPath, outputPdfPath, artistName, releaseTitle, watermark);

    await fs.rename(outputPdfPath, inputPdfPath);

    const metaPath = path.join(EPK_TEMP_DIR, `${jobId}.json`);
    try {
      const metaData = JSON.parse(await fs.readFile(metaPath, 'utf-8'));
      metaData.stamped = true;
      metaData.stampedAt = Date.now();
      await fs.writeFile(metaPath, JSON.stringify(metaData, null, 2));
    } catch (error) {
      console.error('[EPK Compose] Failed to update job meta:', error);
    }

    console.log(`[EPK Compose] Stamped PDF for job ${jobId}`);

    return NextResponse.json({
      ok: true,
      jobId,
      message: 'PDF stamped successfully',
    });
  } catch (error) {
    console.error('[EPK Compose] Error:', error);

    if (error instanceof z.ZodError) {
      return NextResponse.json({
        ok: false,
        error: 'Invalid request data',
        details: error.errors,
      }, { status: 400 });
    }

    return NextResponse.json({
      ok: false,
      error: error instanceof Error ? error.message : 'Failed to compose PDF',
    }, { status: 500 });
  }
}
